name: hiervaeLOHC
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py310hea6c23e_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h34a4b09_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - chemprop=1.6.1=pyhd8ed1ab_1
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.12.0.46=h2b6041c_0
  - cusparselt=0.7.0.0=hcd2ec93_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclasses=0.8=pyhc8e2a94_3
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - expat=2.7.1=hecca717_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h3406613_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - gnutls=3.6.13=h85f3911_1
  - greenlet=3.2.4=py310hea6c23e_1
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.0=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libblas=3.9.0=20_linux64_mkl
  - libboost=1.84.0=hba137d9_3
  - libboost-python=1.84.0=py310ha2bacc8_7
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=20_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcudnn=9.12.0.46=h24322f0_0
  - libcudnn-dev=9.12.0.46=h2b6041c_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.2.1.3=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_5
  - libgcc-ng=15.2.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.2.0=h69a702a_5
  - libgfortran5=15.2.0=hcd61629_5
  - libglib=2.80.2=hf974151_0
  - libgomp=15.2.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h0af6554_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.43=h2797004_0
  - libpq=16.10=h1cdf469_2
  - libprotobuf=3.21.12=hfc55251_2
  - librdkit=2024.03.6=h04b5189_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h8f9b012_5
  - libstdcxx-ng=15.2.0=h4852527_5
  - libsystemd0=257.3=h3dc2cb9_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libudev1=257.4=h9a4d06a_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightning=2.5.5=pyhd8ed1ab_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.1=py310h68603db_0
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.3.0=py310hf73ecf8_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pycairo=1.27.0=py310h25ff670_0
  - pycparser=2.22=pyh29332c3_1
  - pyg=2.6.1=py310_torch_2.4.0_cu124
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.18=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.4.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - rdkit=2024.03.6=py310hf76b54c_0
  - rdma-core=56.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - regex=2025.11.3=py310h7c4b9e2_0
  - reportlab=4.4.4=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h228f341_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sqlalchemy=2.0.43=py310h7c4b9e2_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.22.1=py310h04b4747_0
  - tomli=2.2.1=pyhe01879c_2
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchtriton=3.0.0=py310
  - torchvision=0.19.1=py310_cu124
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.17.0=pyhd8ed1ab_0
  - typed-argument-parser=1.11.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - abnf==2.2.0
      - alembic==1.17.1
      - annotated-types==0.7.0
      - anyio==4.11.0
      - backoff==2.2.1
      - chardet==5.2.0
      - cint==1.0.0
      - colorlog==6.10.1
      - cryptography==46.0.3
      - diskcache==5.6.3
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - fickling==0.1.4
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gql==4.0.0
      - graphql-core==3.2.7
      - graphviz==0.21
      - intervaltree==3.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kaitaistruct==0.11
      - levenshtein==0.27.1
      - mako==1.3.10
      - multidict==6.7.0
      - optuna==4.5.0
      - pdfminer-six==20250506
      - platformdirs==4.5.0
      - polyfile-weave==0.5.7
      - propcache==0.4.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - rapidfuzz==3.14.1
      - referencing==0.37.0
      - requests-toolbelt==1.0.0
      - rpds-py==0.28.0
      - scipy==1.15.3
      - sentry-sdk==2.43.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stdlib-list==0.11.1
      - tenacity==9.1.2
      - typing-inspection==0.4.2
      - wandb==0.22.3
      - weave==0.52.14
prefix: /home/intern_01/miniconda3/envs/hiervae
